Holy water bead code framework
BrandenEK/Blasphemous.LostDreams pull request #62
Opened 2024-06-20 02:09 UTC by EltonZhang777

Adds RB504 bead code framework
Actual beam code still pending.

2024-06-23 21:59 UTC, BrandenEK requested changes
Overall the code looks like a good start, but you might have to redo these commits since there will be merge conflicts because this bead was supposed to be RB506.  Did you not base your branch off of my 'health-beams' branch, since if you did you should have seen the commit and changes for RB506 stuff?

2024-06-23 21:59 UTC, BrandenEK commented on Blasphemous.LostDreams/Effects/HolyWater.cs
> +
What is going on with the using statements up here?

2024-06-26 01:45 UTC, EltonZhang777 commented on Blasphemous.LostDreams/Effects/HolyWater.cs
> +
My VS2022 automatically adds a lot of using statements automatically when I call for random stuff. I'll develop a habit to delete those unused `using` statements after finishing code

2024-06-26 01:46 UTC, EltonZhang777 commented
I'll move these code to the new branch, while experimenting a way to actually register a mod attack. 

I hope I can figure out how to create a modded attack, I'm getting close to it

2024-06-26 01:46 UTC, closed without merging