adds `EventHandler`s for parrying
BrandenEK/Blasphemous.LostDreams pull request #65
Opened 2024-06-23 06:02 UTC by EltonZhang777

`OnParryFail` triggers both when whiffing a parry and when attempting to parry a non-parriable attack. The 3 other handlers are self-explanatory.

2024-06-23 21:53 UTC, BrandenEK requested changes
I trust you tested this before PRing it, the code looks good except for the two fixes I commented.  However, what was the reason for this? As far as I know, none of the items we have planned rely on parry events.

2024-06-23 21:53 UTC, BrandenEK commented on Blasphemous.LostDreams/Events/EventPatches.cs
> +[HarmonyPatch(typeof(Parry), "RaiseParryEvent")]
Obviously not super necessary, but in order to be consistent, please format these all of these the same way.  The style here is already to inline these one-line method calls, so do that with all of them and not just one.

2024-06-23 21:53 UTC, BrandenEK commented on Blasphemous.LostDreams/Events/EventHandler.cs
> +        if (parry.SuccessParry) { OnParryRiposte?.Invoke(parry); }
Never do this.  If you are going to add curly brackets, they need to be on a new line. To follow good coding practices, only one statement per line.  Fix the two places this happens here

2024-06-24 02:17 UTC, EltonZhang777 commented
There's actually a bead that Schiff proposed, `Feather from a Simurgh`, that benefits from parrying (that's actually my revision to it that Schiff approved of, we can make it simpler anyway). And also I suppose there's gotta be some items that are related to parrying, so if this is not super necessary for the time being, it's good to not put extraneous code in LD project. (I'll use my Screaming Sinners mod to experiment with all the crazy functionalities)

Also, thanks for the good coding practices reminder! I'll definitely follow them in my code.

2024-06-24 02:17 UTC, closed without merging

2024-06-24 12:56 UTC, BrandenEK commented
Ah I see.  Sounds good, once we require the parrying event we can either reopen this pr or make a new one